services:
  mysql:
    image: mysql:8.0
    container_name: mysql_prueba
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PRUEBA_PASSWORD}
      MYSQL_DATABASE: ${DB_PRUEBA_DATABASE}
    ports:
      - "${DB_PRUEBA_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
